anuncios:
    resource: "@AnunciosBundle/Resources/config/routing.yml"
    prefix:   /

propietario:
    resource: "@PropietarioBundle/Resources/config/routing.yml"
    prefix:   /

animales:
    resource: "@AnimalesBundle/Controller/"
    type:     annotation
    prefix:   /
    
propietario:
    resource: "@PropietarioBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
animales_animales:
    resource: "@AnimalesBundle/Resources/config/routing/animales.yml"
    prefix:   /animales
