animales_index:
    path:     /
    defaults: { _controller: "AnimalesBundle:Animales:index" }
    methods:  GET

animales_show:
    path:     /{id}/show
    defaults: { _controller: "AnimalesBundle:Animales:show" }
    methods:  GET

animales_new:
    path:     /new
    defaults: { _controller: "AnimalesBundle:Animales:new" }
    methods:  [GET, POST]

animales_edit:
    path:     /{id}/edit
    defaults: { _controller: "AnimalesBundle:Animales:edit" }
    methods:  [GET, POST]

animales_delete:
    path:     /{id}/delete
    defaults: { _controller: "AnimalesBundle:Animales:delete" }
    methods:  DELETE
