<?php

namespace PropietarioBundle\Repository;

/**
 * PropietarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropietarioRepository extends \Doctrine\ORM\EntityRepository
{
}
