<?php

namespace AnunciosBundle\Repository;

/**
 * AnunciosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnunciosRepository extends \Doctrine\ORM\EntityRepository
{
}
