<?php

namespace AnimalesBundle\Repository;

/**
 * AnimalesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimalesRepository extends \Doctrine\ORM\EntityRepository
{
}
